###
POST http://localhost:5000/register HTTP/1.1
content-type: application/json

{
    "email": "oluwatomiwa5@gmail.com",    
    "password": "hashpassowrd",
    "firstName": "Seun",
    "lastName" : "Tope",
    "phoneNumber": "+2347014216076"
    }

### VERIFY USER

POST http://localhost:5000/verify HTTP/1.1
content-type: application/json

{
    "email": "oluwatomiwa2@gmail.com",    
    "otp": "1862"
}

### LOGIN USER
POST http://localhost:5000/login HTTP/1.1
content-type: application/json

{
   "email": "oluwatomiwa4@gmail.com",
    "password": "hashpassowrd"
}

### RESENDOTP USER
POST http://localhost:5000/resendotp HTTP/1.1
content-type: application/json

{
   "email": "oluwatomiwa5@gmail.com"
}
